server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth_api_route
          uri: lb://auth-api
          predicates:
            - Path=/auth-api/**
          filters:
            - StripPrefix=1
        - id: offline_api_route
          uri: lb://offline-api
          predicates:
            - Path=/offline-api/**
          filters:
            - StripPrefix=1
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/