mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.qihang.sys.api.domain;com.qihang.security.entity;
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启sql日志
#mybatis:
#  mapper-locations: classpath*:mappers/user/*.xml

spring:
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  cloud:
    loadbalancer:
      nacos:
        enabled: true
    nacos:
#      serverAddr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
        usename: nacos
        passowrd: nacos
      config:
        server-addr: 127.0.0.1:8848
  #    gateway:
#      discovery:
#        locator:
#          enabled: true # gateway 可以从 nacos 发现微服务
  config:
    import:
      - nacos:qihang-oms.yaml?refresh=true
  application:
    name: sys-api
server:
  port: 8082



