spring:
#  cloud:
#    nacos:
#      serverAddr: 127.0.0.1:8848
#      discovery:
#        server-addr: 127.0.0.1:8848
#  config:
#    import:
#      - nacos:qihang-oms.yaml?refresh=true
#  application:
#    name: tao-api
#  security:
#    user:
#      name: admin
#      password: password
#    basic:
#      enabled: true
#
## 授权规则
#security:
#  rules:
#    - pattern: /api/**   # 定义需要授权的URL模式
  application:
    name: tao-api
  data:
    # redis 配置
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      # 密码
      #    password: 123321
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/qihang-erp?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: Andy_123

server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.qihang.tao.domain;com.qihang.security.entity;
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启sql日志